Python1811AXF/Pyton1811AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('app.urls', namespace='axf')),
]

Python1811AXF/app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^$', views.home, name='index'),
    url(r'^home/$', views.home, name='home'),   # 首页
    url(r'^market/(\d+)/(\d+)/$', views.market, name='market'), # 闪购超市
    url(r'^cart/$', views.cart, name='cart'),   # 购物车
    url(r'^mine/$', views.mine, name='mine'),   # 我的

    url(r'^login/$', views.login, name='login'),    # 登录
    url(r'^register/$', views.register, name='register'),   # 注册
    url(r'^checkemail/$', views.checkemail, name='checkemail'), # 验证邮箱
    url(r'^logout/$', views.logout, name='logout'), # 退出

    url(r'^addcart/$', views.addcart, name='addcart'), # 加操作
    url(r'^subcart/$', views.subcart, name='subcart'),  # 减操作
    url(r'^changecartstatus/$', views.changecartstatus, name='changecartstatus'),   # 修改购物车记录选中状态
    url(r'^changecartall/$', views.changecartall, name='changecartall'),    # 全选操作


    url(r'^generateorder/$', views.generateorder, name='generateorder'),    # 下单
    url(r'^orderlist/(\d+)/$', views.orderlist, name='orderlist'),
    url(r'^orderdetail/(.+)/$', views.orderdetail, name='orderdetail'),    #　订单详情
    url(r'^pay/$', views.pay, name='pay'),  # 支付
    url(r'^appnotify/$', views.appnotify, name='appnotify'),    # 支付完成后(服务器)
    url(r'^returnview/$', views.returnview, name='returnview'), # 买家支付完成后回到AXF哪个页面(客户端)
]

Python1811AXF/templates/mine/login.html
{% extends 'base/base_h_f.html' %}
{% load static %}
{% block footer %}
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/login.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'mine/js/login.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="login">
        <div class="back">
            <a href="{% url 'axf:mine' %}">
                <span class="glyphicon glyphicon-remove"></span>
            </a>
        </div>

        <form id="login" action="{% url 'axf:login' %}" method="post">
            {% csrf_token %}


            <div class="form-group has-feedback" id="email">
                <div class="input-group">
                    <span class="input-group-addon">邮箱</span>
                    <input type="text" class="form-control" placeholder="邮箱" name="email">
                </div>
                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
            </div>


            <div class="form-group has-feedback" id="password">
                <div class="input-group">
                    <span class="input-group-addon">密码</span>
                    <input type="password" class="form-control" placeholder="密码(数字、字母、下划线)" name="password" maxlength="6">
                </div>
                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
            </div>

            <p style="color: red;" id="err">{{ err }}</p>


{#          如果直接使用input点击，会直接提交给服务器 [假如有错误，也同样提交] #}
            <div id="subButton" class="btn btn-success">登录</div>
        </form>


    </div>
{% endblock %}

Python1811AXF/templates/mine/mine.html
{% extends 'base/base_h_f.html' %}
{% load static %}

{% block title %}
    爱鲜蜂 | 我的
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'mine/js/mine.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="mine">
        <div class="user-wrapper">
            <div class="user-img">
                <img src="/static/mine/img/{{ user.img | default:'axf.png' }}" alt="">
            </div>
            <div class="user-content">
                <p>
                    <span class="glyphicon glyphicon-user"></span>
                    <a href="{% url 'axf:login' %}"> {{ user.name | default:'未登录' }} </a>
                </p>
                <p>
                    <span class="glyphicon glyphicon-align-left"></span>
                    等级: {{ user.rank | default:'请登录' }}
                </p>

                {% if user == None %}
                    <a href="{% url 'axf:register' %}" class="register">
                        注册
                    </a>
                {% endif %}
            </div>
        </div>

        <div class="collect">
            <span class="glyphicon glyphicon-adjust"></span>
            <span>商品收藏</span>
        </div>

        <div class="other">
            <section class="my">
                <span>我的订单</span>

                <a href="#">
                    查看所有订单
                    <i class="glyphicon glyphicon-chevron-right"></i>
                </a>
            </section>

            <section>
                <ul>
                    <li>
                        <a href="{% url 'axf:orderlist' 0 %}">
                            <dl>
                                <dt>
                                    <span class="glyphicon glyphicon-gift"></span>
                                    <span class="badge" style="background: red; color: white">{{ waitpay }}</span>
                                </dt>
                                <dd>待付款</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'axf:orderlist' 1 %}">
                            <dl>
                                <dt>
                                    <span class="glyphicon glyphicon-leaf"></span>
                                    <span class="badge" style="background: red; colo    hite">{{ paydone }}</span>
                                </dt>
                                <dd>待收货</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-fire"></span></dt>
                                <dd>待评价</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-plane"></span></dt>
                                <dd>退款/售后</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </section>

            <section>
                <ul>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-gift"></span></dt>
                                <dd>优惠券</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-leaf"></span></dt>
                                <dd>收货地址</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-fire"></span></dt>
                                <dd>客户/反馈</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-plane"></span></dt>
                                <dd>关于</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </section>

            {% if user %}
                <section class="quit">
                    <a href="{% url 'axf:logout' %}">
                        退出登录
                    </a>
            </section>
            {% endif %}
        </div>
    </div>
{% endblock %}

Python1811AXF/templates/mine/register.html
{% extends 'base/base_h_f.html' %}
{% load static %}
{% block footer %}
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/register.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'mine/js/regist.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="register">
        <div class="back">
            <a href="{% url 'axf:mine' %}">
                <span class="glyphicon glyphicon-remove"></span>
            </a>
        </div>

        <form id="register" action="{% url 'axf:register' %}" method="post">
            {% csrf_token %}


{#           has-error  has-success#}
            <div class="form-group has-feedback" id="email">
                <div class="input-group">
                    <span class="input-group-addon">邮箱</span>
                    <input type="text" class="form-control" placeholder="邮箱" name="email">
                </div>
{#                glyphicon-remove  glyphicon-ok#}
                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
            </div>
            <p style="color: red;" id="err"></p>

            <div class="form-group has-feedback" id="password">
                <div class="input-group">
                    <span class="input-group-addon">密码</span>
                    <input type="password" class="form-control" placeholder="密码(数字、字母、下划线)" name="password" maxlength="6">
                </div>
                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
            </div>

            <div class="form-group has-feedback" id="name">
                <div class="input-group">
                    <span class="input-group-addon">名字</span>
                    <input type="text" class="form-control" placeholder="名字(3~10位)" name="name">
                </div>
                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
            </div>

            <div class="form-group has-feedback" id="phone">
                <div class="input-group">
                    <span class="input-group-addon">手机</span>
                    <input type="text" class="form-control" placeholder="手机号" name="phone" maxlength="11">
                </div>
                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
            </div>

{#          如果直接使用input点击，会直接提交给服务器 [假如有错误，也同样提交] #}
            <div id="subButton" class="btn btn-success">注册</div>
        </form>
    </div>
{% endblock %}