Python1811AXF/Pyton1811AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('app.urls', namespace='axf')),
]

Python1811AXF/app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^$', views.home, name='index'),
    url(r'^home/$', views.home, name='home'),   # 首页
    url(r'^market/(\d+)/(\d+)/$', views.market, name='market'), # 闪购超市
    url(r'^cart/$', views.cart, name='cart'),   # 购物车
    url(r'^mine/$', views.mine, name='mine'),   # 我的

    url(r'^login/$', views.login, name='login'),    # 登录
    url(r'^register/$', views.register, name='register'),   # 注册
    url(r'^checkemail/$', views.checkemail, name='checkemail'), # 验证邮箱
    url(r'^logout/$', views.logout, name='logout'), # 退出

    url(r'^addcart/$', views.addcart, name='addcart'), # 加操作
    url(r'^subcart/$', views.subcart, name='subcart'),  # 减操作
    url(r'^changecartstatus/$', views.changecartstatus, name='changecartstatus'),   # 修改购物车记录选中状态
    url(r'^changecartall/$', views.changecartall, name='changecartall'),    # 全选操作


    url(r'^generateorder/$', views.generateorder, name='generateorder'),    # 下单
    url(r'^orderlist/(\d+)/$', views.orderlist, name='orderlist'),
    url(r'^orderdetail/(.+)/$', views.orderdetail, name='orderdetail'),    #　订单详情
    url(r'^pay/$', views.pay, name='pay'),  # 支付
    url(r'^appnotify/$', views.appnotify, name='appnotify'),    # 支付完成后(服务器)
    url(r'^returnview/$', views.returnview, name='returnview'), # 买家支付完成后回到AXF哪个页面(客户端)
]

Python1811AXF/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/reset.css' %}">

    {% block extbasecss %}
    {% endblock %}
</head>
<body>

{% block body %}

{% endblock %}

{#<scirpt src="{% static 'base/js/jquery.min.js' %}"></scirpt>#}
{#<scirpt src="{% static 'base/js/jquery.js' %}"></scirpt>#}
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
<script src="{% static 'base/js/base.js' %}"></script>
<scirpt src="{% static 'base/js/bootstrap.min.js' %}"></scirpt>
{% block extbasejs %}
{% endblock %}
</body>
</html>

Python1811AXF/templates/base/base_h_f.html
{% extends 'base/base.html' %}
{% load static %}

{% block extbasecss %}
    <link rel="stylesheet" href="{% static 'base/css/base_h_f.css' %}">
    {% block extcss %}
    {% endblock %}
{% endblock %}

{% block extbasejs %}
    <script src="{% static 'base/js/base_h_f.js' %}"></script>
    {% block extjs %}
    {% endblock %}
{% endblock %}

{% block body %}
{#    头部#}
    {% block header %}
        <header>爱鲜蜂</header>
    {% endblock %}

{#    主体内容#}
    <div class="hidescroll">
        <div id="content">
            {% block content %}

            {% endblock %}
        </div>
    </div>

{#    尾部#}
    {% block footer %}
        <footer>
            <a href="{% url 'axf:home' %}" class="home">
                <dl>
                    <dt> <span></span> </dt>
                    <dd>首页</dd>
                </dl>
            </a>
            <a href="{% url 'axf:market' 0 1  %}" class="market">
                <dl>
                    <dt> <span></span> </dt>
                    <dd>闪购超市</dd>
                </dl>
            </a>
            <a href="{% url 'axf:cart' %}" class="cart">
                <dl>
                    <dt> <span></span> </dt>
                    <dd>购物车</dd>
                </dl>
            </a>
            <a href="{% url 'axf:mine' %}" class="mine">
                <dl>
                    <dt> <span></span> </dt>
                    <dd>我的</dd>
                </dl>
            </a>
        </footer>
    {% endblock %}
{% endblock %}